server:
  port: 9090

spring:
  application:
    name: 'spring-project-second'

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver